// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixmul_matrixmul,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu50-fsvh2104-2L-e,HLS_INPUT_CLOCK=13.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.862000,HLS_SYN_LAT=17,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=234,HLS_SYN_LUT=317,HLS_VERSION=2022_1}" *)

module matrixmul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        b_dout,
        b_empty_n,
        b_read,
        a_dout,
        a_empty_n,
        a_read,
        res_din,
        res_full_n,
        res_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] b_dout;
input   b_empty_n;
output   b_read;
input  [23:0] a_dout;
input   a_empty_n;
output   a_read;
output  [15:0] res_din;
input   res_full_n;
output   res_write;

reg ap_idle;
reg b_read;
reg a_read;
reg res_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] select_ln58_1_reg_454;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln70_reg_458;
reg   [0:0] icmp_ln70_reg_458_pp0_iter1_reg;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln63_fu_187_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    a_blk_n;
wire    ap_block_pp0_stage0;
reg    b_blk_n;
reg    res_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] select_ln58_fu_211_p3;
reg   [1:0] select_ln58_reg_449;
wire   [0:0] select_ln58_1_fu_237_p3;
wire   [0:0] icmp_ln70_fu_253_p2;
reg   [1:0] b_copy_addr_reg_462;
reg   [1:0] b_copy_addr_reg_462_pp0_iter2_reg;
reg   [1:0] b_copy_addr_reg_462_pp0_iter3_reg;
reg   [1:0] b_copy_1_addr_reg_467;
reg   [1:0] b_copy_1_addr_reg_467_pp0_iter2_reg;
reg   [1:0] b_copy_2_addr_reg_472;
reg   [7:0] a_row_load_reg_477;
reg  signed [7:0] a_row_load_reg_477_pp0_iter4_reg;
reg  signed [7:0] a_row_1_load_reg_482;
wire  signed [15:0] mul_ln82_fu_383_p2;
wire   [15:0] grp_fu_389_p3;
wire   [1:0] b_copy_address0;
reg    b_copy_ce0;
reg    b_copy_we0;
wire   [7:0] b_copy_d0;
reg    b_copy_ce1;
wire  signed [7:0] b_copy_q1;
wire   [1:0] b_copy_1_address0;
reg    b_copy_1_ce0;
reg    b_copy_1_we0;
wire   [7:0] b_copy_1_d0;
reg    b_copy_1_ce1;
wire  signed [7:0] b_copy_1_q1;
wire   [1:0] b_copy_2_address0;
reg    b_copy_2_ce0;
reg    b_copy_2_we0;
wire   [7:0] b_copy_2_d0;
reg    b_copy_2_ce1;
wire  signed [7:0] b_copy_2_q1;
wire   [63:0] zext_ln65_fu_280_p1;
reg   [1:0] j_fu_66;
wire   [1:0] add_ln65_fu_259_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_load;
reg   [1:0] i_fu_70;
wire   [1:0] select_ln63_fu_245_p3;
reg   [1:0] ap_sig_allocacmp_i_load;
reg   [3:0] indvar_flatten_fu_74;
wire   [3:0] add_ln63_fu_193_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [7:0] a_row_fu_78;
wire   [7:0] a_row_3_fu_313_p1;
reg   [7:0] a_row_1_fu_82;
reg  signed [7:0] a_row_2_fu_86;
wire   [15:0] grp_fu_397_p3;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln65_fu_205_p2;
wire   [1:0] add_ln63_1_fu_219_p2;
wire   [0:0] cmp14_mid1_fu_225_p2;
wire   [0:0] cmp144_fu_231_p2;
reg    grp_fu_389_ce;
reg    grp_fu_397_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_221;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrixmul_b_copy_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
b_copy_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_copy_address0),
    .ce0(b_copy_ce0),
    .we0(b_copy_we0),
    .d0(b_copy_d0),
    .address1(b_copy_addr_reg_462_pp0_iter3_reg),
    .ce1(b_copy_ce1),
    .q1(b_copy_q1)
);

matrixmul_b_copy_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
b_copy_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_copy_1_address0),
    .ce0(b_copy_1_ce0),
    .we0(b_copy_1_we0),
    .d0(b_copy_1_d0),
    .address1(b_copy_1_addr_reg_467_pp0_iter2_reg),
    .ce1(b_copy_1_ce1),
    .q1(b_copy_1_q1)
);

matrixmul_b_copy_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
b_copy_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_copy_2_address0),
    .ce0(b_copy_2_ce0),
    .we0(b_copy_2_we0),
    .d0(b_copy_2_d0),
    .address1(b_copy_2_addr_reg_472),
    .ce1(b_copy_2_ce1),
    .q1(b_copy_2_q1)
);

matrixmul_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U1(
    .din0(b_copy_q1),
    .din1(a_row_load_reg_477_pp0_iter4_reg),
    .dout(mul_ln82_fu_383_p2)
);

matrixmul_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_copy_2_q1),
    .din1(a_row_2_fu_86),
    .din2(mul_ln82_fu_383_p2),
    .ce(grp_fu_389_ce),
    .dout(grp_fu_389_p3)
);

matrixmul_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_copy_1_q1),
    .din1(a_row_1_load_reg_482),
    .din2(grp_fu_389_p3),
    .ce(grp_fu_397_ce),
    .dout(grp_fu_397_p3)
);

matrixmul_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_221)) begin
        if ((icmp_ln63_fu_187_p2 == 1'd0)) begin
            i_fu_70 <= select_ln63_fu_245_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_70 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_221)) begin
        if ((icmp_ln63_fu_187_p2 == 1'd0)) begin
            indvar_flatten_fu_74 <= add_ln63_fu_193_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_74 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_221)) begin
        if ((icmp_ln63_fu_187_p2 == 1'd0)) begin
            j_fu_66 <= add_ln65_fu_259_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_66 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln70_reg_458_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        a_row_1_fu_82 <= {{a_dout[15:8]}};
        a_row_2_fu_86 <= {{a_dout[23:16]}};
        a_row_fu_78 <= a_row_3_fu_313_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        a_row_1_load_reg_482 <= a_row_1_fu_82;
        a_row_load_reg_477 <= a_row_fu_78;
        a_row_load_reg_477_pp0_iter4_reg <= a_row_load_reg_477;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        b_copy_1_addr_reg_467_pp0_iter2_reg <= b_copy_1_addr_reg_467;
        b_copy_addr_reg_462_pp0_iter2_reg <= b_copy_addr_reg_462;
        b_copy_addr_reg_462_pp0_iter3_reg <= b_copy_addr_reg_462_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        b_copy_1_addr_reg_467 <= zext_ln65_fu_280_p1;
        b_copy_2_addr_reg_472 <= zext_ln65_fu_280_p1;
        b_copy_addr_reg_462 <= zext_ln65_fu_280_p1;
        icmp_ln70_reg_458_pp0_iter1_reg <= icmp_ln70_reg_458;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln63_fu_187_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln70_reg_458 <= icmp_ln70_fu_253_p2;
        select_ln58_1_reg_454 <= select_ln58_1_fu_237_p3;
        select_ln58_reg_449 <= select_ln58_fu_211_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln70_reg_458_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        a_blk_n = a_empty_n;
    end else begin
        a_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln70_reg_458_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        a_read = 1'b1;
    end else begin
        a_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln63_fu_187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (select_ln58_1_reg_454 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_blk_n = b_empty_n;
    end else begin
        b_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_copy_1_ce0 = 1'b1;
    end else begin
        b_copy_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        b_copy_1_ce1 = 1'b1;
    end else begin
        b_copy_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (select_ln58_1_reg_454 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_copy_1_we0 = 1'b1;
    end else begin
        b_copy_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_copy_2_ce0 = 1'b1;
    end else begin
        b_copy_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        b_copy_2_ce1 = 1'b1;
    end else begin
        b_copy_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (select_ln58_1_reg_454 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_copy_2_we0 = 1'b1;
    end else begin
        b_copy_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_copy_ce0 = 1'b1;
    end else begin
        b_copy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        b_copy_ce1 = 1'b1;
    end else begin
        b_copy_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (select_ln58_1_reg_454 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_copy_we0 = 1'b1;
    end else begin
        b_copy_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (select_ln58_1_reg_454 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_read = 1'b1;
    end else begin
        b_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_389_ce = 1'b1;
    end else begin
        grp_fu_389_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_397_ce = 1'b1;
    end else begin
        grp_fu_397_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        res_blk_n = res_full_n;
    end else begin
        res_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        res_write = 1'b1;
    end else begin
        res_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_row_3_fu_313_p1 = a_dout[7:0];

assign add_ln63_1_fu_219_p2 = (ap_sig_allocacmp_i_load + 2'd1);

assign add_ln63_fu_193_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln65_fu_259_p2 = (select_ln58_fu_211_p3 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((res_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((icmp_ln70_reg_458_pp0_iter1_reg == 1'd1) & (1'b0 == a_empty_n) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((select_ln58_1_reg_454 == 1'd1) & (b_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((res_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((icmp_ln70_reg_458_pp0_iter1_reg == 1'd1) & (1'b0 == a_empty_n) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((select_ln58_1_reg_454 == 1'd1) & (b_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((res_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((icmp_ln70_reg_458_pp0_iter1_reg == 1'd1) & (1'b0 == a_empty_n) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((select_ln58_1_reg_454 == 1'd1) & (b_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((select_ln58_1_reg_454 == 1'd1) & (b_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln70_reg_458_pp0_iter1_reg == 1'd1) & (1'b0 == a_empty_n));
end

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = (res_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_221 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_copy_1_address0 = zext_ln65_fu_280_p1;

assign b_copy_1_d0 = {{b_dout[15:8]}};

assign b_copy_2_address0 = zext_ln65_fu_280_p1;

assign b_copy_2_d0 = {{b_dout[23:16]}};

assign b_copy_address0 = zext_ln65_fu_280_p1;

assign b_copy_d0 = b_dout[7:0];

assign cmp144_fu_231_p2 = ((ap_sig_allocacmp_i_load == 2'd0) ? 1'b1 : 1'b0);

assign cmp14_mid1_fu_225_p2 = ((add_ln63_1_fu_219_p2 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_187_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_205_p2 = ((ap_sig_allocacmp_j_load == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_253_p2 = ((select_ln58_fu_211_p3 == 2'd0) ? 1'b1 : 1'b0);

assign res_din = grp_fu_397_p3;

assign select_ln58_1_fu_237_p3 = ((icmp_ln65_fu_205_p2[0:0] == 1'b1) ? cmp14_mid1_fu_225_p2 : cmp144_fu_231_p2);

assign select_ln58_fu_211_p3 = ((icmp_ln65_fu_205_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j_load);

assign select_ln63_fu_245_p3 = ((icmp_ln65_fu_205_p2[0:0] == 1'b1) ? add_ln63_1_fu_219_p2 : ap_sig_allocacmp_i_load);

assign zext_ln65_fu_280_p1 = select_ln58_reg_449;

endmodule //matrixmul
